import {Footer} from '@/components/common/Footer';

import './globals.css';
import {Header} from '../components/common/Header';
import {WithFonts} from '../components/common/WithFonts';

import type {Metadata} from 'next';
import type {ReactNode} from 'react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>): ReactNode {
	return (
		<html lang={'en'}>
			<body className={'bg-white text-black antialiased'}>
				<WithFonts>
					<Header />
					{children}
					<Footer />
				</WithFonts>
			</body>
		</html>
	);
}
