import {RootWrapper} from '@/components/common/RootWrapper';

import './globals.css';

import type {Metadata} from 'next';
import type {ReactNode} from 'react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>): ReactNode {
	return (
		<html lang={'en'}>
			<body className={'bg-white text-black antialiased'}>
				<RootWrapper>{children}</RootWrapper>
			</body>
		</html>
	);
}
